### ISSUE TITLE
Doesn't work with simpla-img

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-link#3]
`simpla-img` doesn't properly maintain its focus when the global editor singleton opens. The editor steals focus from simpla-link, causing it to blur. 

To fix this simpla-img should fire a `focusin` event on the original `img` element when it opens the editor, to retain consistent focusing behavior for any parent items, since the editor is meant to look like it originates from the img element.

**Comment by madeleineostoja** [comment]
As of https://github.com/SimplaElements/simpla-link/commit/14816b5c6df6c2871deedd81dee1016c6e2dbda7 just firing `focusin` on the img won't work, because simpla-link now checks for what element in the document is actually in focus (`document.activeElement`) when closing... not sure how to remedy.

@bedeoverend any ideas?

**Comment by bedeoverend** [comment]
Not off the top of my head. Rather than trying to dummy it up to make `simpla-img` look like it's still in focus, maybe we should just add a custom event that, if it reaches `simpla-link` will keep it in focus? Essentially I think making our own API of some kind to control whether it stays in focus or not would be best, otherwise I think we'll just end up in a world of pain trying to trick the DOM into thinking something else is in focus. 

By our own API I mean something like `retain-focus` which link could check for after a `focusout` event (from the item that lost focus) e.g.

```js
_onFocusout(event) {
  event.target.addEventListener('retain-focus', ...);
} 
```
or some such. Or even just a property or callback on the `event.target`. Just some way to ask the blurred item that it is actually being blurred.

**Comment by madeleineostoja** [comment]
That would fail if simpla-link is used on anything but simpla elements, which is much more fragile. We should patch the simpla-img issue instead, since it's simpla-img's fault that it loses focus when it's active, since it's meant to behave like the image itself is focussed but our global singleton messes it up. _It_ should be the one that is more robust.

Simpla-link should just expect that its children get focus when they are active, and not try to be any cleverer than that.

**Comment by bedeoverend** [comment]
Yeah that's true. Unfortunately something somewhere is gonna have to be clever - but you're right it's better for img to be the one doing it, and just leave link all clean and simple.

**Comment by madeleineostoja** [comment]
This is fixed with latest simpla-img (had to revert to more robust `document.activeElement` check in close, since we're faking focusout w/ simpla-img).
